# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'

target 'PRM' do
  # Uncomment this line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for PRM
  pod 'SDCycleScrollView', '~> 1.65'
  pod 'AFNetworking', '~> 3.1.0'
  pod 'SDWebImage', '~> 3.8.1'
  pod 'MJRefresh', '~> 3.1.12'
  pod 'Masonry', '~> 1.0.1'
 
  pod 'PinYin4Objc', '~> 1.1.1'
 
  pod 'BRPickerView', '~> 2.2.1'

end
