# Uncomment the next line to define a global platform for your project
 platform :ios, '9.0'

target 'PRM' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for PRM
pod 'AFNetworking', '~> 3.2.1'
pod 'SDWebImage', '~> 4.2.1'
pod 'Masonry', '~> 1.1.0'
pod 'QMUIKit', '~> 3.0.0'
pod 'MJRefresh', '~> 3.1.15.7'
pod 'BRPickerView', '~> 2.2.1'
pod 'YYKit'


pod 'PYPhotoBrowser', '~> 1.5.6'
#pod 'PYSearch', '~> 0.9.1'







end
